### ISSUE TITLE
SP Combined Search -> techn. correction: Einführung von "mii-provision-code-type" und "mii-provision-code-period"

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#17]
Argument: muss beides zusammen abgerufen werden, da FHIR sonst nicht die gewünschten Ergebnisse liefert. Beispiele für die Definition der SP folgen - die Jungs testen das gerade und liefern funktionierende Definitionen für diese combined SP.

**ToDos**
- [x] 1. Diese Search Parameter ergänzen:
  - [x] mii-provision-code-type
  - [x] mii-provision-code-period
  - [x] Definition dieser Search Parameter
    - [x] @juliangruendner bitte in diesem Ticket ergänzen.

- [x] 2. IG
  - [x] Hinweis im IG, dass diese Composit Searches in Components mit dem HAPI-Server aktuell nicht funktionieren.
  - [x] IG neue Search Parameter einfügen und beschreiben
  - [x] IG exportieren
  - [x] IG Export auf der MII Homepage publizieren

**Comment by juliangruendner** [comment]
@lhitc, @SebStaeubert  - below a suggestion for the search parameters:
please double check the search params and adjust them accordingly.

I have successfully tested the search parameters using blaze and hapi with two exceptions:
For hapi the composite search param could not be tested as it does not handle composite search params ind components correctly
For blaze the composite search param with date (mii-provision-provision-code-period) is currently not supported - but will be implemented in the next months.

=> mii-provision-provision-code-type could only be tested on blaze
=> mii-provision-provision-code-period could not be tested

`[
  {
    "resourceType": "SearchParameter",
    "id": "mii-provision-provision-code",
    "url": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisioncode",
    "version": "1.0.3",
    "name": "MII_SP_Consent_ProvisionCode",
    "status": "active",
    "date": "2023-03-08",
    "description": "Suche im Code der Provison",
    "code": "mii-provision-provision-code",
    "base": [
      "Consent"
    ],
    "type": "token",
    "expression": "Consent.provision.provision.code"
  },
  {
    "resourceType": "SearchParameter",
    "id": "mii-provision-provision-type",
    "url": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisiontype",
    "version": "1.0.3",
    "name": "MII_SP_Consent_ProvisionType",
    "status": "active",
    "date": "2023-03-08",
    "description": "Suche im Typ (type) der Provison",
    "code": "mii-provision-provision-type",
    "base": [
      "Consent"
    ],
    "type": "token",
    "expression": "Consent.provision.provision.type"
  },
  {
    "resourceType": "SearchParameter",
    "id": "mii-provision-provision-period",
    "url": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisionperiod",
    "version": "1.0.3",
    "name": "MII_SP_Consent_ProvisionPeriod",
    "status": "active",
    "date": "2023-03-08",
    "description": "Suche im Zeitraum (period) der Provison",
    "code": "mii-provision-provision-period",
    "base": [
      "Consent"
    ],
    "type": "date",
    "expression": "Consent.provision.provision.period"
  },
  {
    "resourceType": "SearchParameter",
    "id": "mii-provision-provision-code-type",
    "url": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisioncodetype",
    "version": "1.0.3",
    "name": "MII_SP_Consent_ProvisionCodeType",
    "status": "active",
    "date": "2023-03-08",
    "description": "Suche nach Typ (type) einer bestimmten, durch einen Code definierten, Provision",
    "code": "mii-provision-provision-code-type",
    "base": [
      "Consent"
    ],
    "type": "composite",
    "expression": "Consent.provision.provision",
    "component": [
      {
        "definition": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisioncode",
        "expression": "code"
      },
      {
        "definition": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisiontype",
        "expression": "type"
      }
    ]
  },
  {
    "resourceType": "SearchParameter",
    "id": "mii-provision-provision-code-period",
    "url": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisioncodeperiod",
    "version": "1.0.3",
    "name": "MII_SP_Consent_ProvisionCodePeriod",
    "status": "active",
    "date": "2023-03-08",
    "description": "Suche nach Zeitraum (period) einer bestimmten, durch einen Code definierten, Provision",
    "code": "mii-provision-provision-code-period",
    "base": [
      "Consent"
    ],
    "type": "composite",
    "expression": "Consent.provision.provision",
    "component": [
      {
        "definition": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisioncode",
        "expression": "code"
      },
      {
        "definition": "https://www.medizininformatik-initiative.de/fhir/modul-consent/SearchParameter/mii-sp-consent-provisionperiod",
        "expression": "period"
      }
    ]
  }
]`

**Comment by lhitc** [comment]
@SebStaeubert IG ist exportiert; nach Veröffentlichung bitte dieses Issue schließen.

**Comment by SebStaeubert** [comment]
Erledigt: https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Consent/IGMIIKDSModulConsent.html
