### ISSUE TITLE
Policy CodeSystem/ValueSet -> techn. correction: Umbenennung der Labels

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#19]
**ToDos**
- [x] aktuelle Display Names -> Designation...
- [x] Unterstriche entfernen und durch sprechende Bezeichner ersetzen
- [x] ART-DECOR: https://art-decor.org/art-decor/decor-valuesets--mide-?id=2.16.840.1.113883.3.1937.777.24.11.36
- [ ] FHIR CodeSystem, ValueSet, IG aktualisieren

Achtung: CodeSystem(e) aktuell von KDS Onko gekapert -> gefixt!
