### ISSUE TITLE
[PM] KDS Modul Consent v2026 erstellen, aktualisieren, prüfen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/kerndatensatzmodul-consent#59]
### ToDo allgemein

- [ ] Welche Anforderungen aus der AG Consent gibt es?
- [ ] Tickets prüfen und dem Meilenstein https://github.com/medizininformatik-initiative/kerndatensatzmodul-consent/milestone/2 zuweisen
- [ ] [Tickets / Features HL7-De AG Einwilligungsmanagement](https://github.com/hl7germany/einwilligungsmanagement/issues) prüfen und ggf. aufnehmen
- [ ] [aktuelle KDS-Template "* 2023+"](https://simplifier.net/guide/medizininformatikinitiative-implementationguide-template?version=current) beachten: https://simplifier.net/MedizininformatikInitiative-Kerndatensatz/~guides
- [ ] core / ext in der URL (Structure Definition Profile) entfernen
